# render.yaml
services:
  - type: web
    name: ai-quizzer-api
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: DB_TYPE
        value: mongo
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_SECURE
        value: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
